### ISSUE TITLE
TypeErrors when clicking "Show Details"

### ISSUE THREAD

**Issue by adamkorynta** [jzillmann/gradle-jmh-report#10]
It looks like the JavaScript run isn't the same as what is available on the live instance at: https://jmh.morethan.io/ which works for the given input.

```
bundle.js:45 TypeError: Cannot read properties of undefined (reading 'forEach')
    at t.value (bundle.js:53:1024905)
    at bundle.js:53:981582
    at Array.forEach (<anonymous>)
    at bundle.js:53:981480
    at Array.map (<anonymous>)
    at Ex (bundle.js:53:981419)
    at bundle.js:53:987179
    at t.value (bundle.js:53:987713)
    at Co (bundle.js:45:62702)
    at Bo (bundle.js:45:67586)
Uo @ bundle.js:45
bundle.js:45 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at t.value (bundle.js:53:1024905)
    at bundle.js:53:981582
    at Array.forEach (<anonymous>)
    at bundle.js:53:981480
    at Array.map (<anonymous>)
    at Ex (bundle.js:53:981419)
    at bundle.js:53:987179
    at t.value (bundle.js:53:987713)
    at Co (bundle.js:45:62702)
    at Bo (bundle.js:45:67586)
```

Attached the input file:
[benchmark.json](https://github.com/jzillmann/gradle-jmh-report/files/14951061/benchmark.json)

**Comment by jzillmann** [comment]
Thanks for reporting. `0.9.6` is now up with the same code of the website!
